services:
  - name: auth-system-api
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn <project_name>.wsgi:application --preload
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        sync: false
